# Generated by Django 4.0.1 on 2025-03-13 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HosteriaSol', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallereserva',
            name='precio_unitario',
        ),
        migrations.AddField(
            model_name='detallereserva',
            name='precio_neto',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='reserva',
            name='empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fk05_idEmpleado', to='HosteriaSol.empleado'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='pago',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fk06_idPago', to='HosteriaSol.pago'),
        ),
        migrations.AlterField(
            model_name='detallereserva',
            name='cantidad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='detallereserva',
            name='habitacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk02_idHabitacion', to='HosteriaSol.habitacion'),
        ),
        migrations.AlterField(
            model_name='detallereserva',
            name='reserva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk01_idReserva', to='HosteriaSol.reserva'),
        ),
        migrations.AlterField(
            model_name='detalleservicio',
            name='detalle_reserva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fk07_idDetalleReserva', to='HosteriaSol.detallereserva'),
        ),
        migrations.AlterField(
            model_name='detalleservicio',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk03_idServicio', to='HosteriaSol.servicio'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='habitacion',
            name='descripcion',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='habitacion',
            name='precio',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='pago',
            name='monto_total',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fk04_idCliente', to='HosteriaSol.usuario'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='servicio_adicional',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='descripcion',
            field=models.TextField(default='sin descripcion'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='estado',
            field=models.CharField(choices=[('Activo', 'ACTIVO'), ('Inactivo', 'INACTIVO')], default='activo', max_length=8),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='precio',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.IntegerField(choices=[('Administrador', 'ADMINISTRADOR'), ('Empleado', 'EMPLEADO'), ('Recepcionista', 'RECEPCIONISTA'), ('Cliente', 'CLIENTE')], default=4),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo_documento',
            field=models.CharField(choices=[('CC', 'Cedula de Ciudadania'), ('TI', 'Tarjeta de Identidad'), ('CE', 'Cedula de Extranjeria'), ('P', 'Pasaporte')], max_length=2),
        ),
    ]
