# Generated by Django 5.1.6 on 2025-03-26 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HosteriaSol', '0004_remove_reserva_servicio_adicional_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='metodo_pago',
            field=models.IntegerField(choices=[(1, 'EFECTIVO'), (2, 'TRANSFERENCIA'), (3, 'DATAFONO')], default=2),
        ),
    ]
