# Generated by Django 5.1.6 on 2025-03-26 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HosteriaSol', '0005_alter_pago_metodo_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo_documento',
            field=models.IntegerField(choices=[(1, 'Cedula de Ciudadania'), (2, 'Tarjeta de Identidad'), (3, 'Cedula de Extranjeria'), (4, 'Pasaporte')], default=1),
        ),
    ]
