# Generated by Django 5.1.6 on 2025-03-26 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HosteriaSol', '0007_remove_reserva_fecha_reserva_reserva_fecha_fin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='fecha_fin',
            field=models.DateTimeField(blank=True, help_text='AAAA-MM-DD', null=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='fecha_inicio',
            field=models.DateTimeField(blank=True, help_text='AAAA-MM-DD', null=True),
        ),
    ]
