# Generated by Django 5.1.6 on 2025-03-26 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HosteriaSol', '0010_alter_reserva_fecha_fin_alter_reserva_fecha_inicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='num_personas',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
