# Generated by Django 5.1.6 on 2025-03-26 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HosteriaSol', '0011_reserva_num_personas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.IntegerField(choices=[(1, 'Administrador'), (2, 'Empleado'), (3, 'Cliente')], default=3),
        ),
    ]
