# Generated by Django 5.1.6 on 2025-03-26 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HosteriaSol', '0013_alter_servicio_estado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='num_personas',
            new_name='num_per',
        ),
    ]
