# Generated by Django 5.1.6 on 2025-03-27 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HosteriaSol', '0014_rename_num_personas_reserva_num_per'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='estado',
            field=models.CharField(choices=[('Activo', 'ACTIVO'), ('Inactivo', 'INACTIVO')], default='Activo', max_length=8),
        ),
    ]
