# Generated by Django 5.1.6 on 2025-03-27 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HosteriaSol', '0015_pago_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pago',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='apellido',
        ),
    ]
