# Generated by Django 5.1.6 on 2025-03-27 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HosteriaSol', '0016_remove_pago_estado_remove_usuario_apellido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='documento',
            field=models.CharField(max_length=20),
        ),
    ]
