# Generated by Django 4.0.1 on 2025-04-01 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HosteriaSol', '0018_alter_usuario_correo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('A', 'ACTIVA'), ('I', 'INACTIVA'), ('C', 'CANCELADA'), ('P', 'PAGADA')], default='A', max_length=1),
        ),
    ]
