# Generated by Django 4.0.1 on 2025-04-01 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HosteriaSol', '0019_alter_reserva_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(default='usuarios/default.png', max_length=254, upload_to='usuarios'),
        ),
    ]
