# Generated by Django 5.1.6 on 2025-04-01 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HosteriaSol', '0023_alter_reserva_empleado_alter_reserva_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fk04_idCliente', to='HosteriaSol.usuario'),
            preserve_default=False,
        ),
    ]
