# Generated by Django 5.1.6 on 2025-04-01 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HosteriaSol', '0024_alter_reserva_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fk04_idCliente', to='HosteriaSol.usuario'),
        ),
    ]
