# Generated by Django 5.1.6 on 2025-04-01 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HosteriaSol', '0025_alter_reserva_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fk04_idCliente', to='HosteriaSol.usuario'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reserva',
            name='empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fk05_idEmpleado', to='HosteriaSol.empleado'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='pago',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fk06_idPago', to='HosteriaSol.pago'),
        ),
    ]
