# Generated by Django 5.1.6 on 2025-04-03 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HosteriaSol', '0027_alter_reserva_cliente_alter_reserva_empleado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pago',
            name='hora',
        ),
        migrations.AlterField(
            model_name='pago',
            name='fecha_pago',
            field=models.DateTimeField(),
        ),
    ]
