# Generated by Django 4.0.1 on 2025-04-03 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HosteriaSol', '0029_alter_usuario_correo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='metodo_pago',
            field=models.IntegerField(choices=[('Efectivo', 'EFECTIVO'), ('Tranferencia', 'TRANSFERENCIA'), ('Datafono', 'DATAFONO')], default='Tranferencia'),
        ),
    ]
