# Generated by Django 5.1.6 on 2025-04-03 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HosteriaSol', '0030_alter_pago_metodo_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='metodo_pago',
            field=models.IntegerField(choices=[(1, 'EFECTIVO'), (2, 'TRANSFERENCIA'), (3, 'DATAFONO')], default=1),
        ),
    ]
