# Generated by Django 5.1.7 on 2025-04-06 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HosteriaSol', '0031_alter_pago_metodo_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitacion',
            name='foto',
            field=models.ImageField(default='habitaciones/default.png', max_length=254, upload_to='habitaciones'),
        ),
    ]
