# Generated by Django 5.1.6 on 2025-04-09 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HosteriaSol', '0033_servicio_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='foto',
            field=models.ImageField(default='servicios/default.jpg', max_length=254, upload_to='servicios/'),
        ),
    ]
