# Generated by Django 5.1.6 on 2025-04-10 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HosteriaSol', '0035_alter_servicio_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='estado',
            field=models.IntegerField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default=1),
        ),
    ]
