# Generated by Django 4.0.1 on 2025-04-11 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HosteriaSol', '0037_alter_servicio_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='activo',
            field=models.BooleanField(default=False),
        ),
    ]
