# Generated by Django 5.1.6 on 2025-04-21 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HosteriaSol', '0038_usuario_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='pago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fk06_idPago', to='HosteriaSol.pago'),
        ),
    ]
