# Generated by Django 5.1.7 on 2025-04-28 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HosteriaSol', '0039_alter_reserva_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='fecha_pago',
            field=models.DateTimeField(null=True),
        ),
    ]
