# Generated by Django 5.1.6 on 2025-05-04 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HosteriaSol', '0040_alter_pago_fecha_pago'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empleado',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='habitacion',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='reserva',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='servicio',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ['-id']},
        ),
    ]
