# Generated by Django 5.1.6 on 2025-05-04 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HosteriaSol', '0041_alter_empleado_options_alter_habitacion_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleado',
            old_name='email',
            new_name='correo',
        ),
    ]
