# Generated by Django 5.1.6 on 2025-05-04 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HosteriaSol', '0043_rename_num_per_reserva_adultos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='foto',
            field=models.ImageField(default='empleados/default.png', max_length=254, upload_to='empleados'),
        ),
    ]
