# Generated by Django 5.1.6 on 2025-05-04 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HosteriaSol', '0044_empleado_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='foto',
            field=models.ImageField(default='/media/empleados/default.png', max_length=254, upload_to='empleados'),
        ),
    ]
