# Generated by Django 5.1.6 on 2025-05-05 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HosteriaSol', '0046_alter_empleado_foto_alter_usuario_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='foto',
            field=models.ImageField(default='/media/empleados/default.png', max_length=254, upload_to='empleados'),
        ),
    ]
