# Generated by Django 5.1.6 on 2025-05-05 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HosteriaSol', '0047_alter_empleado_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='password',
            field=models.CharField(default='123', max_length=100),
        ),
    ]
