# Generated by Django 5.1.6 on 2025-05-05 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HosteriaSol', '0048_empleado_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
