# Generated by Django 5.1.6 on 2025-05-05 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HosteriaSol', '0050_alter_usuario_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='direccion',
            field=models.CharField(default='Sin dirección', max_length=254),
        ),
        migrations.AddField(
            model_name='empleado',
            name='documento',
            field=models.CharField(default='00000000', max_length=20),
        ),
        migrations.AddField(
            model_name='empleado',
            name='rol',
            field=models.IntegerField(choices=[(1, 'Administrador'), (2, 'Cliente'), (3, 'Empleado')], default=3),
        ),
        migrations.AddField(
            model_name='empleado',
            name='telefono',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='tipo_documento',
            field=models.IntegerField(choices=[(1, 'Cedula de Ciudadania'), (2, 'Tarjeta de Identidad'), (3, 'Cedula de Extranjeria'), (4, 'Pasaporte')], default=1),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.IntegerField(choices=[(1, 'Administrador'), (2, 'Cliente'), (3, 'Empleado')], default=2),
        ),
    ]
