# Generated by Django 5.1.6 on 2025-05-05 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HosteriaSol', '0051_empleado_direccion_empleado_documento_empleado_rol_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='documento',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='rol',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='telefono',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='tipo_documento',
        ),
    ]
