# Generated by Django 5.1.6 on 2025-05-05 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HosteriaSol', '0052_remove_empleado_direccion_remove_empleado_documento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.IntegerField(choices=[(1, 'Administrador'), (2, 'Cliente')], default=2),
        ),
    ]
