# Generated by Django 5.1.6 on 2025-05-05 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HosteriaSol', '0053_alter_usuario_rol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='password',
        ),
    ]
