# Generated by Django 5.1.6 on 2025-05-05 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HosteriaSol', '0054_remove_empleado_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='foto',
        ),
    ]
