# Generated by Django 4.2.9 on 2025-05-05 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HosteriaSol', '0057_alter_empleado_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='foto',
            field=models.ImageField(default='empleados/default.png', max_length=254, upload_to='empleados'),
        ),
    ]
