# Generated by Django 5.1.6 on 2025-05-08 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HosteriaSol', '0060_alter_empleado_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
