# Generated by Django 4.2.9 on 2025-05-08 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HosteriaSol', '0061_empleado_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.IntegerField(choices=[(1, 'Administrador'), (2, 'Cliente'), (3, 'Empleado')], default=2),
        ),
    ]
