# Generated by Django 5.2.1 on 2025-05-16 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HosteriaSol', '0062_alter_usuario_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('A', 'ACTIVA'), ('I', 'INACTIVA'), ('C', 'CANCELADA'), ('P', 'PAGADA'), ('V', 'VENCIDA')], default='A', max_length=1),
        ),
    ]
